# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choix.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Laser.Views.laserui import Ui_MainWindow


class OpenView(object):

    def __init__(self):
        """
        instantiates a welcome window to select the laser muquans you want.
        """
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.label = QtWidgets.QLabel(Form)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton_2 = QtWidgets.QPushButton(Form)

    def setupUi(self, openwindow):
        """
        Setup the UI, changing the fonts and colors in css.
        :param openwindow: this is the UI window
        :return: None
        """
        openwindow.setObjectName("Form")
        openwindow.resize(578, 414)
        openwindow.setStyleSheet("QWidget{\n"
                                 "    background-color:#303030;\n"
                                 "    color:#FDFAEB;\n"
                                 "}")
        self.gridLayout.setObjectName("gridLayout")
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(30)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)

        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(30)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color:#FFF9D4;\n"
                                      "    color:#303030;\n"
                                      "    border-radius: 10px;\n"
                                      "    transition-duration: 0.4s;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "  background-color: #D4DAFF; \n"
                                      "  color:#FDFAEB;\n"
                                      "}")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)

        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(30)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color:#FFF9D4;\n"
                                        "    border-radius: 10px;\n"
                                        "    color:#303030;\n"
                                        "    transition-duration: 0.4s;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "  background-color: #D4DAFF; \n"
                                        "  color:#FDFAEB;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton.clicked.connect(self.openKapaz)
        self.pushButton_2.clicked.connect(self.openShargdhag)
        self.pushButton.clicked.connect(openwindow.close)
        self.pushButton_2.clicked.connect(openwindow.close)

        self.verticalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)

        icon = QtGui.QIcon("images/logo.png")
        openwindow.setWindowIcon(icon)

        self.retranslateUi(openwindow)
        QtCore.QMetaObject.connectSlotsByName(openwindow)
        openwindow.setTabOrder(self.pushButton, self.pushButton_2)

    def openKapaz(self):
        """
        open Kapaz
        :return: None
        """
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(host="192.168.1.108", channel=2)
        self.ui.setupUi(self.window)
        self.window.show()

    def openShargdhag(self):
        """
        open Shargdhag
        :return: None
        """
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(host="192.168.1.107", channel=1)
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, openwindow):
        """
        write txt on UI
        :param openwindow: yes
        :return: None
        """
        _translate = QtCore.QCoreApplication.translate
        openwindow.setWindowTitle(_translate("Form", " "))
        self.label.setText(_translate("Form", "Choose your Laser "))
        self.pushButton.setText(_translate("Form", "Kapaz"))
        self.pushButton_2.setText(_translate("Form", "Shakhdag"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = OpenView()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())