# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choix.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Classes.ClassRedPitaya import MyRedpitaya
from Views.laserui import Ui_MainWindow


class OpenView(object):

    def __init__(self, Form):
        """
        instantiates a welcome window to select the laser muquans you want.
        """
        self.Form = Form
        self.gridLayout = QtWidgets.QGridLayout(self.Form)
        self.label = QtWidgets.QLabel(self.Form)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.pushButton = QtWidgets.QPushButton(self.Form)
        self.pushButton_2 = QtWidgets.QPushButton(self.Form)

    def setupUi(self, openwindow):
        """
        Setup the UI, changing the fonts and colors in css.
        :param openwindow: this is the UI window
        :return: None
        """
        openwindow.setObjectName("Form")
        openwindow.resize(578, 414)
        openwindow.setStyleSheet("QWidget{\n"
                                 "    background-color:#303030;\n"
                                 "    color:#FDFAEB;\n"
                                 "}")
        self.gridLayout.setObjectName("gridLayout")
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(30)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)

        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(30)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color:#FFF9D4;\n"
                                      "    color:#303030;\n"
                                      "    border-radius: 10px;\n"
                                      "    transition-duration: 0.4s;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "  background-color: #D4DAFF; \n"
                                      "  color:#FDFAEB;\n"
                                      "}")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)

        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(30)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color:#FFF9D4;\n"
                                        "    border-radius: 10px;\n"
                                        "    color:#303030;\n"
                                        "    transition-duration: 0.4s;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "  background-color: #D4DAFF; \n"
                                        "  color:#FDFAEB;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton.clicked.connect(self.openKapaz)
        self.pushButton_2.clicked.connect(self.openShargdhag)
        self.pushButton.clicked.connect(openwindow.close)
        self.pushButton_2.clicked.connect(openwindow.close)

        self.verticalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)

        icon = QtGui.QIcon("images/logo.png")
        openwindow.setWindowIcon(icon)

        self.retranslateUi(openwindow)
        QtCore.QMetaObject.connectSlotsByName(openwindow)
        openwindow.setTabOrder(self.pushButton, self.pushButton_2)

    def openKapaz(self):
        """
        open Kapaz
        :return: None
        """
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(host="192.168.1.108", channel=2)
        self.ui.setupUi(self.window)
        self.window.show()

    def openShargdhag(self):
        """
        open Shargdhag
        :return: None
        """
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(host="192.168.1.107", channel=1)
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, openwindow):
        """
        write txt on UI
        :param openwindow: yes
        :return: None
        """
        _translate = QtCore.QCoreApplication.translate
        openwindow.setWindowTitle(_translate("Form", " "))
        self.label.setText(_translate("Form", "Choose your Laser "))
        self.pushButton.setText(_translate("Form", "Kapaz"))
        self.pushButton_2.setText(_translate("Form", "Shakhdag"))


class PulseSignals(Ui_MainWindow):

    def __init__(self, addr=None, output=None):
        self.addr = addr
        self.output = output
        self.red = MyRedpitaya()
        self.MainWindow = QtWidgets.QMainWindow()
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.lineEdit_offset = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_frequency = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_amplitude = QtWidgets.QLineEdit(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.lineEdit_amplitude.setText('10')
        self.lineEdit_frequency.setText('1')
        self.lineEdit_offset.setText('0')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "    background-color : #303030;\n"
                                         "     color : #FDFAEB;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.setObjectName("gridLayout")
        self.label_3.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        sizePolicy.setHeightForWidth(self.lineEdit_offset.sizePolicy().hasHeightForWidth())
        self.lineEdit_offset.setSizePolicy(sizePolicy)
        self.lineEdit_offset.setStyleSheet("QLineEdit{\n"
                                           "    background-color:#f6f6f6;\n"
                                           "    border: 2px solid gray;\n"
                                           "    border-radius: 5px;\n"
                                           "    padding: 0 8px;\n"
                                           "    selection-background-color: darkgray;\n"
                                           "    font-size: 16px;\n"
                                           "    color: #303030;"
                                           "}\n"
                                           "\n"
                                           " QLineEdit:focus { \n"
                                           "    background-color#f6f6f6;\n"
                                           "}\n"
                                           "")
        self.lineEdit_offset.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_offset, 3, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_frequency.sizePolicy().hasHeightForWidth())
        self.lineEdit_frequency.setSizePolicy(sizePolicy)
        self.lineEdit_frequency.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_frequency.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_frequency, 2, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_amplitude.sizePolicy().hasHeightForWidth())
        self.lineEdit_amplitude.setSizePolicy(sizePolicy)
        self.lineEdit_amplitude.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_amplitude.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_amplitude, 1, 0, 1, 1)
        self.label_2.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color:#FFF9D4;\n"
                                      "    color:#303030;\n"
                                      "    border-radius: 8px;\n"
                                      "    transition-duration: 0.4s;\n"
                                      "    height:40px;\n"
                                      "    width:115px;\n"
                                      "    color: #303030;"
                                      "}\n"
                                      "                      \n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #D4DAFF; \n"
                                      "    color:#FDFAEB;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.setSignal)
        self.pushButton.clicked.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setSignal(self):
        amplitude = float(self.lineEdit_amplitude.text())
        frequency = float(self.lineEdit_frequency.text())
        offset = float(self.lineEdit_offset.text())
        self.red.set_pulse(output=self.output, frequency=frequency, amplitude=amplitude, offset=offset)

    def retranslateUi(self, MainWindow):
        """
        write txt on UI
        :param MainWindow: yes
        :return: void
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.label.setText(_translate("MainWindow", "Pulse"))
        self.label_4.setText(_translate("MainWindow", "Offset [V]"))
        self.label_2.setText(_translate("MainWindow", "Amplitude [V]"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))


class RampSignals(Ui_MainWindow):
    def __init__(self, addr=None, output=None):
        self.addr = addr
        self.output = output
        self.red = MyRedpitaya()
        self.RampWindow = QtWidgets.QMainWindow()
        self.centralwidget = QtWidgets.QWidget(self.RampWindow)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.lineEdit_offset = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_frequency = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_amplitude = QtWidgets.QLineEdit(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)

        self.lineEdit_amplitude.setText('10')
        self.lineEdit_frequency.setText('1')
        self.lineEdit_offset.setText('0')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "    background-color : #303030;\n"
                                         "     color : #FDFAEB;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.setObjectName("gridLayout")
        self.label_3.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)

        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.label_4.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_offset.sizePolicy().hasHeightForWidth())
        self.lineEdit_offset.setSizePolicy(sizePolicy)
        self.lineEdit_offset.setStyleSheet("QLineEdit{\n"
                                           "    background-color:#f6f6f6;\n"
                                           "    border: 2px solid gray;\n"
                                           "    border-radius: 5px;\n"
                                           "    padding: 0 8px;\n"
                                           "    selection-background-color: darkgray;\n"
                                           "    font-size: 16px;\n"
                                           "    color: #303030;"
                                           "}\n"
                                           "\n"
                                           " QLineEdit:focus { \n"
                                           "    background-color#f6f6f6;\n"
                                           "}\n"
                                           "")
        self.lineEdit_offset.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_offset, 3, 0, 1, 1)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_frequency.sizePolicy().hasHeightForWidth())
        self.lineEdit_frequency.setSizePolicy(sizePolicy)
        self.lineEdit_frequency.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_frequency.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_frequency, 2, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_amplitude.sizePolicy().hasHeightForWidth())
        self.lineEdit_amplitude.setSizePolicy(sizePolicy)
        self.lineEdit_amplitude.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_amplitude.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_amplitude, 1, 0, 1, 1)
        self.label_2.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color:#FFF9D4;\n"
                                      "    color:#303030;\n"
                                      "    border-radius: 8px;\n"
                                      "    transition-duration: 0.4s;\n"
                                      "    height:40px;\n"
                                      "    width:115px;\n"
                                      "    color: #303030;"
                                      "}\n"
                                      "                      \n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #D4DAFF; \n"
                                      "    color:#FDFAEB;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.setSignal)
        self.pushButton.clicked.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setSignal(self):
        amplitude = float(self.lineEdit_amplitude.text())
        frequency = float(self.lineEdit_frequency.text())
        offset = float(self.lineEdit_offset.text())
        self.red.set_ramp(output=self.output, frequency=frequency, amplitude=amplitude, offset=offset)

    def retranslateUi(self, MainWindow):
        """
        write txt on UI
        :param MainWindow: yes
        :return: void
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.label.setText(_translate("MainWindow", "Ramp"))
        self.label_4.setText(_translate("MainWindow", "Offset [V]"))
        self.label_2.setText(_translate("MainWindow", "Amplitude [V]"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))


class SineSignals(Ui_MainWindow):
    def __init__(self, addr=None, output=None):
        self.addr = addr
        self.output = output
        self.red = MyRedpitaya()
        self.MainWindow = QtWidgets.QMainWindow()
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.lineEdit_frequency = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_amplitude = QtWidgets.QLineEdit(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.lineEdit_amplitude.setText('10')
        self.lineEdit_frequency.setText('1')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "    background-color : #303030;\n"
                                         "     color : #FDFAEB;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.setObjectName("gridLayout")
        self.label_3.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_frequency.sizePolicy().hasHeightForWidth())
        self.lineEdit_frequency.setSizePolicy(sizePolicy)
        self.lineEdit_frequency.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_frequency.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_frequency, 2, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_amplitude.sizePolicy().hasHeightForWidth())
        self.lineEdit_amplitude.setSizePolicy(sizePolicy)
        self.lineEdit_amplitude.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_amplitude.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_amplitude, 1, 0, 1, 1)
        self.label_2.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color:#FFF9D4;\n"
                                      "    color:#303030;\n"
                                      "    border-radius: 8px;\n"
                                      "    transition-duration: 0.4s;\n"
                                      "    height:40px;\n"
                                      "    width:115px;\n"
                                      "    color: #303030;"
                                      "}\n"
                                      "                      \n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #D4DAFF; \n"
                                      "    color:#FDFAEB;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.setSignal)
        self.pushButton.clicked.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setSignal(self):
        amplitude = float(self.lineEdit_amplitude.text())
        frequency = float(self.lineEdit_frequency.text())
        self.red.set_sine(output=self.output, frequency=frequency, amplitude=amplitude)

    def retranslateUi(self, MainWindow):
        """
        write txt on UI
        :param MainWindow: yes
        :return: void
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.label.setText(_translate("MainWindow", "Sine"))
        self.label_2.setText(_translate("MainWindow", "Amplitude [V]"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))


class SquareSignals(Ui_MainWindow):
    def __init__(self, addr=None, output=None):
        self.addr = addr
        self.output = output
        self.red = MyRedpitaya()
        self.MainWindow = QtWidgets.QMainWindow()
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.lineEdit_offset = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_frequency = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_amplitude = QtWidgets.QLineEdit(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)

        self.lineEdit_amplitude.setText('10')
        self.lineEdit_frequency.setText('1')
        self.lineEdit_offset.setText('0')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "    background-color : #303030;\n"
                                         "     color : #FDFAEB;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.setObjectName("gridLayout")
        self.label_3.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
                                 "    background-color : #303030;\n"
                                 "     color : #FDFAEB;\n"
                                 "}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_offset.sizePolicy().hasHeightForWidth())
        self.lineEdit_offset.setSizePolicy(sizePolicy)
        self.lineEdit_offset.setStyleSheet("QLineEdit{\n"
                                           "    background-color:#f6f6f6;\n"
                                           "    border: 2px solid gray;\n"
                                           "    border-radius: 5px;\n"
                                           "    padding: 0 8px;\n"
                                           "    selection-background-color: darkgray;\n"
                                           "    font-size: 16px;\n"
                                           "    color: #303030;"
                                           "}\n"
                                           "\n"
                                           " QLineEdit:focus { \n"
                                           "    background-color#f6f6f6;\n"
                                           "}\n"
                                           "")
        self.lineEdit_offset.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_offset, 3, 0, 1, 1)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_frequency.sizePolicy().hasHeightForWidth())
        self.lineEdit_frequency.setSizePolicy(sizePolicy)
        self.lineEdit_frequency.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_frequency.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_frequency, 2, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_amplitude.sizePolicy().hasHeightForWidth())
        self.lineEdit_amplitude.setSizePolicy(sizePolicy)
        self.lineEdit_amplitude.setStyleSheet("QLineEdit{\n"
                                              "    background-color:#f6f6f6;\n"
                                              "    border: 2px solid gray;\n"
                                              "    border-radius: 5px;\n"
                                              "    padding: 0 8px;\n"
                                              "    selection-background-color: darkgray;\n"
                                              "    font-size: 16px;\n"
                                              "    color: #303030;"
                                              "}\n"
                                              "\n"
                                              " QLineEdit:focus { \n"
                                              "    background-color#f6f6f6;\n"
                                              "}\n"
                                              "")
        self.lineEdit_amplitude.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_amplitude, 1, 0, 1, 1)
        self.label_2.setStyleSheet("QLabel {\n"
                                   "    background-color : #303030;\n"
                                   "     color : #FDFAEB;\n"
                                   "}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color:#FFF9D4;\n"
                                      "    color:#303030;\n"
                                      "    border-radius: 8px;\n"
                                      "    transition-duration: 0.4s;\n"
                                      "    height:40px;\n"
                                      "    width:115px;\n"
                                      "    color: #303030;"
                                      "}\n"
                                      "                      \n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #D4DAFF; \n"
                                      "    color:#FDFAEB;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.setSignal)
        self.pushButton.clicked.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setSignal(self):
        amplitude = float(self.lineEdit_amplitude.text())
        frequency = float(self.lineEdit_frequency.text())
        offset = float(self.lineEdit_offset.text())
        self.red.set_square(output=self.output, frequency=frequency, amplitude=amplitude, offset=offset)

    def retranslateUi(self, MainWindow):
        """
        write txt on UI
        :param MainWindow: yes
        :return: None
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.label.setText(_translate("MainWindow", "Square"))
        self.label_4.setText(_translate("MainWindow", "Offset [V]"))
        self.label_2.setText(_translate("MainWindow", "Amplitude [V]"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
